name: tplm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.37
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - ffmpeg=4.3
  - filelock=3.15.4
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.0.15
  - libcurand=10.3.7.37
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.5
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.3
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.3.1
  - pillow=9.4.0
  - pip=24.2
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.14
  - python_abi=3.10
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=72.1.0
  - sympy=1.13.0
  - tbb=2021.12.0
  - tk=8.6.13
  - torchaudio=2.2.2
  - torchtriton=2.2.0
  - torchvision=0.17.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.2
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - fsspec==2024.6.1
      - huggingface-hub==0.24.5
      - inquirerpy==0.3.4
      - joblib==1.4.2
      - numpy==1.26.4
      - packaging==24.1
      - pfzy==0.3.4
      - prompt-toolkit==3.0.47
      - scikit-learn==1.3.1
      - scipy==1.14.0
      - threadpoolctl==3.5.0
      - tqdm==4.66.5
      - wcwidth==0.2.13
