# Training Parameters
training:
  batch_size: 4096
  learning_rate: 0.00226274169
  iteration: 120

directories:
  train: "data/aav/aav_train.tsv"
  validation: "data/aav/aav_val.tsv"
  test: "data/aav/aav_test.tsv"
