# Training Parameters
training:
  batch_size: 4096
  learning_rate: 0.00226274169
  iteration: 120

directories:
  train: "data/meltome/meltome_train.tsv"
  validation: "data/meltome/meltome_val.tsv"
  test: "data/meltome/meltome_test.tsv"
